# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers

class DetailedException1(object):
    __slots__ = ['_tab']

    # DetailedException1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetailedException1
    def _exceptionValue(self): return self._tab.Get(flatbuffers.number_types.Uint64Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))

def CreateDetailedException1(builder, ExceptionValue):
    builder.Prep(8, 8)
    builder.PrependUint64(ExceptionValue)
    return builder.Offset()
