# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers

class DetailedException3(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDetailedException3(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetailedException3()
        x.Init(buf, n + offset)
        return x

    # DetailedException3
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetailedException3
    def AType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DetailedException3
    def A(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def DetailedException3Start(builder): builder.StartObject(2)
def DetailedException3AddAType(builder, AType): builder.PrependUint8Slot(0, AType, 0)
def DetailedException3AddA(builder, A): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(A), 0)
def DetailedException3End(builder): return builder.EndObject()
