# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

class OverallLikelyException4Union(object):
    NONE = 0
    DetailedException2 = 1
    DetailedException4 = 2

