# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers

class DetailedException1Vector(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDetailedException1Vector(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetailedException1Vector()
        x.Init(buf, n + offset)
        return x

    # DetailedException1Vector
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetailedException1Vector
    def A(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 8
            from .DetailedException1 import DetailedException1
            obj = DetailedException1()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DetailedException1Vector
    def ALength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def DetailedException1VectorStart(builder): builder.StartObject(1)
def DetailedException1VectorAddA(builder, A): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(A), 0)
def DetailedException1VectorStartAVector(builder, numElems): return builder.StartVector(8, numElems, 8)
def DetailedException1VectorEnd(builder): return builder.EndObject()
