# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class DetailedException2Vector(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetailedException2Vector()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDetailedException2Vector(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DetailedException2Vector
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetailedException2Vector
    def A(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DetailedException2()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DetailedException2Vector
    def ALength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DetailedException2Vector
    def AIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DetailedException2VectorStart(builder): builder.StartObject(1)
def Start(builder):
    return DetailedException2VectorStart(builder)
def DetailedException2VectorAddA(builder, a): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(a), 0)
def AddA(builder, a):
    return DetailedException2VectorAddA(builder, a)
def DetailedException2VectorStartAVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def StartAVector(builder, numElems):
    return DetailedException2VectorStartAVector(builder, numElems)
def DetailedException2VectorEnd(builder): return builder.EndObject()
def End(builder):
    return DetailedException2VectorEnd(builder)