# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers

class DetailedException1(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDetailedException1(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetailedException1()
        x.Init(buf, n + offset)
        return x

    # DetailedException1
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetailedException1
    def _exceptionValue(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def DetailedException1Start(builder): builder.StartObject(1)
def DetailedException1Add_exceptionValue(builder, ExceptionValue): builder.PrependUint64Slot(0, ExceptionValue, 0)
def DetailedException1End(builder): return builder.EndObject()
