# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers

class DetailedException4(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDetailedException4(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetailedException4()
        x.Init(buf, n + offset)
        return x

    # DetailedException4
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetailedException4
    def _code(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # DetailedException4
    def _message(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DetailedException4Start(builder): builder.StartObject(2)
def DetailedException4Add_code(builder, Code): builder.PrependUint64Slot(0, Code, 0)
def DetailedException4Add_message(builder, Message): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(Message), 0)
def DetailedException4End(builder): return builder.EndObject()
