# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

import flatbuffers

class DetailedException3Vector(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsDetailedException3Vector(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DetailedException3Vector()
        x.Init(buf, n + offset)
        return x

    # DetailedException3Vector
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DetailedException3Vector
    def AType(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # DetailedException3Vector
    def ATypeAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # DetailedException3Vector
    def ATypeLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DetailedException3Vector
    def A(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Union(a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # DetailedException3Vector
    def ALength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def DetailedException3VectorStart(builder): builder.StartObject(2)
def DetailedException3VectorAddAType(builder, AType): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(AType), 0)
def DetailedException3VectorStartATypeVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def DetailedException3VectorAddA(builder, A): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(A), 0)
def DetailedException3VectorStartAVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def DetailedException3VectorEnd(builder): return builder.EndObject()
