// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace OMTLS.FlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum OverallLikelyExceptionUnion : byte
{
  NONE = 0,
  DetailedException1 = 1,
  DetailedException2 = 2,
};

public struct DetailedException1 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static DetailedException1 GetRootAsDetailedException1(ByteBuffer _bb) { return GetRootAsDetailedException1(_bb, new DetailedException1()); }
  public static DetailedException1 GetRootAsDetailedException1(ByteBuffer _bb, DetailedException1 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DetailedException1 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong _ExceptionValue { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<OMTLS.FlatBuffers.DetailedException1> CreateDetailedException1(FlatBufferBuilder builder,
      ulong _exceptionValue = 0) {
    builder.StartTable(1);
    DetailedException1.Add_ExceptionValue(builder, _exceptionValue);
    return DetailedException1.EndDetailedException1(builder);
  }

  public static void StartDetailedException1(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void Add_ExceptionValue(FlatBufferBuilder builder, ulong _ExceptionValue) { builder.AddUlong(0, _ExceptionValue, 0); }
  public static Offset<OMTLS.FlatBuffers.DetailedException1> EndDetailedException1(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<OMTLS.FlatBuffers.DetailedException1>(o);
  }
}

public struct DetailedException2 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static DetailedException2 GetRootAsDetailedException2(ByteBuffer _bb) { return GetRootAsDetailedException2(_bb, new DetailedException2()); }
  public static DetailedException2 GetRootAsDetailedException2(ByteBuffer _bb, DetailedException2 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DetailedException2 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string _ExceptionValue { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> Get_ExceptionValueBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? Get_ExceptionValueBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] Get_ExceptionValueArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<OMTLS.FlatBuffers.DetailedException2> CreateDetailedException2(FlatBufferBuilder builder,
      StringOffset _exceptionValueOffset = default(StringOffset)) {
    builder.StartTable(1);
    DetailedException2.Add_ExceptionValue(builder, _exceptionValueOffset);
    return DetailedException2.EndDetailedException2(builder);
  }

  public static void StartDetailedException2(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void Add_ExceptionValue(FlatBufferBuilder builder, StringOffset _ExceptionValueOffset) { builder.AddOffset(0, _ExceptionValueOffset.Value, 0); }
  public static Offset<OMTLS.FlatBuffers.DetailedException2> EndDetailedException2(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<OMTLS.FlatBuffers.DetailedException2>(o);
  }
}

public struct DetailedException3 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static DetailedException3 GetRootAsDetailedException3(ByteBuffer _bb) { return GetRootAsDetailedException3(_bb, new DetailedException3()); }
  public static DetailedException3 GetRootAsDetailedException3(ByteBuffer _bb, DetailedException3 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DetailedException3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public OMTLS.FlatBuffers.OverallLikelyExceptionUnion AType { get { int o = __p.__offset(4); return o != 0 ? (OMTLS.FlatBuffers.OverallLikelyExceptionUnion)__p.bb.Get(o + __p.bb_pos) : OMTLS.FlatBuffers.OverallLikelyExceptionUnion.NONE; } }
  public TTable? A<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public OMTLS.FlatBuffers.DetailedException1 AAsDetailedException1() { return A<OMTLS.FlatBuffers.DetailedException1>().Value; }
  public OMTLS.FlatBuffers.DetailedException2 AAsDetailedException2() { return A<OMTLS.FlatBuffers.DetailedException2>().Value; }

  public static Offset<OMTLS.FlatBuffers.DetailedException3> CreateDetailedException3(FlatBufferBuilder builder,
      OMTLS.FlatBuffers.OverallLikelyExceptionUnion A_type = OMTLS.FlatBuffers.OverallLikelyExceptionUnion.NONE,
      int AOffset = 0) {
    builder.StartTable(2);
    DetailedException3.AddA(builder, AOffset);
    DetailedException3.AddAType(builder, A_type);
    return DetailedException3.EndDetailedException3(builder);
  }

  public static void StartDetailedException3(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddAType(FlatBufferBuilder builder, OMTLS.FlatBuffers.OverallLikelyExceptionUnion aType) { builder.AddByte(0, (byte)aType, 0); }
  public static void AddA(FlatBufferBuilder builder, int aOffset) { builder.AddOffset(1, aOffset, 0); }
  public static Offset<OMTLS.FlatBuffers.DetailedException3> EndDetailedException3(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<OMTLS.FlatBuffers.DetailedException3>(o);
  }
}


}
