# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatBuffers

class OverallLikelyExceptionUnion(object):
    NONE = 0
    DetailedException1 = 1
    DetailedException2 = 2

